export const ar = {

    Categories: " الاصناف",
    Add: "اضافة",
    AddNewcategory: "إضاف تصنيف جديد",
    NameofthenewcategoryinArabic: "الاسم بالعربية",
    NameofthenewcategoryinEnglish: "الاسم بالإنجليزية",
    NoItems: "لم يتم العثور على العناصر",
    EGP: "جنية",
    Edit: "تعديل",
    CreateNewItem: "إنشاء عنصر جديد",
    Save: "حفظ",
    NameofthenewIteminArabic: "الاسم بالعربية",
    NameofthenewIteminEnglish: "الاسم بالإنجليزية",
    ItemName: "اسم العنصر",
    ItemDescription: "وصف العنصر",
    Order: "ترتيب",
    OrderplaceHolder: "رقم ترتيب العنصر",
    Price: "السعر",
    PriceplaceHolder: "سعر العنصر",
    TooShort: "قصير جدا!",
    TooLong: "طويل جدا!",
    Required: "مطلوب",
    Settings: "الاعدادات",
    LanguageSettings: "اعدادات اللغة",
    Allowuserstochangethelanguage: "السماح للمستخدمين بتغيير اللغة",
    defaultlanguage: "اللغة الافتراضية",
    Arabic: "عربي",
    English: "English",
    Advertisingmedia: "وسائط الدعاية والإعلان",
    offers: "عروض",
    Promotionalvideo: "فيديو ترويجي",
    Login: "تسجيل الدخول",
    Password: "كلمة المرور",
    CodeorEmail: "رمز أو بريد إلكتروني",
    Menumanagementsystem: "نظام إدارة القائمة",
    Welcomeback: "مرحبًا بعودتك!",
    Modified: "تم التعديل",
    Areyousuredeletingthecategory: "هل أنت متأكد من حذف الفئة؟",
    Yesdeleteit: "نعم ، احذفها!",
    cancel: "الغاء",
    deleted: "تم الحذف",
    AreyousuredeletingtheItem: "هل أنت متأكد من حذف العنصر؟",
    register: "انشاء حساب جديد",
    or: "او",
    now: "الأن",
    Donthaveaccount: "ليس لديك حساب؟",
    createanaccount: "إنشاء حساب",
    signin: "تسجيل الدخول",
    haveaccount: "لديك حساب؟",
    Name: "أدخل أسمك",
    Email: "أدخل بريدك الإلكتروني",
    phoneNumber: "أدخل رقم هاتفك",
    userName: "اختر اسم المستخدم",
    cPassword: "تأكيد كلمة المرور",
    Passwordsmustmatch: "يجب أن تتطابق كلمات المرور",
    Anewaccounthasbeencreated: "تم انشاء حساب جديد",
    Wewillcallyousoon: "سنتصل بك قريبا",
    Thisuseralreadyexists: "هذا المستخدم موجود مسبقا",
    Dashboard: "لوحة التحكم",
    menu: "قائمة طعام",
    Subscribers: "المشتركين",
    subscriptiontime: "وقت الاشتراك",
    PlaceName: "اسم المكان",
    Status: "الحالة",
    search: "بحث",

}