export const en = {
  Categories: "Categories",
  Add: "Add",
  AddNewcategory: "Add new category",
  NameofthenewcategoryinArabic: "Arabic Name",
  NameofthenewcategoryinEnglish: "English Name",
  NoItems: "No items found",
  EGP: "EGP",
  Edit: "Edit",
  CreateNewItem: "Create new item",
  Save: "Save",
  NameofthenewIteminArabic: "Arabic Name",
  NameofthenewIteminEnglish: "English Name",
  ItemName: "Item name",
  ItemDescription: "Item description",
  Order: "Order",
  OrderplaceHolder: "Item order number",
  Price: "Price",
  PriceplaceHolder: "Item price",
  TooShort: "Too short!",
  TooLong: "Too long!",
  Required: "Required",
  Settings: "Settings",
  LanguageSettings: "Language settings",
  Allowuserstochangethelanguage: "Allow users to change the language",
  defaultlanguage: "Default language",
  Arabic: "عربي",
  English: "English",
  Advertisingmedia: "Advertising media",
  offers: "Offers",
  Promotionalvideo: "Promotional video",
  Login: "Login",
  Password: "Password",
  CodeorEmail: "Code or Email",
  Menumanagementsystem: "Menu management system",
  Welcomeback: "Welcome back!",
  Modified: "Modified",
  Areyousuredeletingthecategory: "Are you sure deleting this category?",
  Yesdeleteit: "Yes, delete it!",
  cancel: "Cancel",
  deleted: "Deleted",
  AreyousuredeletingtheItem: "Are you sure deleting this Item?",
  register: "Register",
  or: "or",
  now: "now",
  Donthaveaccount: "Don't have account?",
  createanaccount: "Create an account",
  signin: "Signin",
  haveaccount: "Have account?",
  Name: "Enter your Name",
  Email: "Email",
  phoneNumber: "phone number",
  userName: "Choose username",
  cPassword: "Confirm password",
  Passwordsmustmatch: "Passwords must match",
  Anewaccounthasbeencreated: "A new account has been created",
  Wewillcallyousoon: "We will call you soon",
  Thisuseralreadyexists: "This user already exists",
  Dashboard: "Dashboard",
  menu: "Menu",
  Subscribers: "Subscribers",
  subscriptiontime: "Subscription time",
  PlaceName: "Place name",
  Status: "Status",
  search: "Search",
  Connectus: "contact us",
  Leaveyourmessageandwewillgetbacktoyou:
    "Leave your message and we will get back to you",
  submit: "Submit",
  YourMessage: "Your Message",
  Enteryouremail: "Enter your email",
  EnterYourphonenumber: "Enter Your phone number",
  Enteryourmessageorinquiry: "Enter your message or inquiry",
  Enteravalidphonenumber: "Enter a valid phone number",
  Message: "Messages",
  Time: "Time",
  Delete: "Delete",
  View: "View",
  AddNewClient: "Add new client",
  Allsubscribedcustomers: "All subscribed customers",

  chooseClientlogo: "Choose client logo",
  chooseClientcolor: "Choose logo color",
  ClientName: "Client name",
  placeName: "Place name",
  EnterClientName: "Enter client name",
  EnterplaceName: "Enter place name",

  PhoneNumber: "Phone number",
  EnterPhoneNumber: "Enter phone number",
  EmailAddress: "Email",
  EnterEmailAddress: "Enter email",
  Anerroroccurred: "An error occurred",
};